name: Publish A Private NPM package
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        default: '0.0.1-alpha.1'
        description: will be put in 'version' field of package.json. Should not duplicate with existing version. e.g.'0.0.1-alpha.1'
jobs:
  publish-private-npm-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install contract dependencies
        run: npm ci
        env:
          CI: true

      - name: Build contract package
        run: npm run build
        env:
          CI: true

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@perpetual-protocol'

      - name: Publish npm package
        run: |
          echo "${{ github.event.inputs.version }}"
          npm pkg set name="@perpetual-protocol/lushan"
          npm pkg set version="${{ github.event.inputs.version }}"
          npm pkg set repository.url="https://github.com/perpetual-protocol/perp-lushan.git"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "npm package @perpetual-protocol/lushan@${{ github.event.inputs.version }} ${{github.ref}} released on github package"
